openapi: 3.0.1
info:
  title: Peakflo API
  description: 'The Peakflo API follows REST. Our APIs are organised as resource-oriented URLs, returns JSON responses.  They return standard HTTP response codes. You will need a JWT token to access the resources you are authorized to. '
  contact:
    url: 'https://peakflo.co/'
    email: info@peakflo.co
  x-logo:
    url: 'https://assets.dorik.com/5fa7a91326674600114e7aca/images/logo_black_zv0e3kxb.png'
    altText: Peakflo logo
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  url: 'https://docs.peakflo.co'
servers:
  - url: 'https://virtserver.swaggerhub.com/hari3/customer/1.0.0'
tags:
  - name: Customer
    description: The customer
  - name: Contact
    description: The customers contact
paths:
  /customer:
    post:
      tags:
        - Customer
      summary: Add a customer
      description: Add a new customer
      operationId: add-customer
      requestBody:
        description: Customer to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: false
      responses:
        '201':
          description: customer created
          content: {}
        '400':
          description: 'invalid input, object invalid'
          content: {}
        '409':
          description: an existing customer already exists
          content: {}
      x-codegen-request-body-name: Customer
    parameters: []
  '/customer/{id}':
    put:
      tags:
        - Customer
      summary: 'Update a customer '
      description: Update a existing customer
      operationId: update-customer
      parameters:
        - name: id
          in: path
          description: The customer externalRefNumber
          required: true
          schema:
            type: string
      requestBody:
        description: Customer to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: false
      responses:
        '201':
          description: customer updated
          content: {}
        '400':
          description: 'invalid input, object invalid'
          content: {}
        '409':
          description: customer doesnot exist
          content: {}
      x-codegen-request-body-name: Customer
    delete:
      summary: ''
      operationId: delete-customer
      responses:
        '200':
          description: OK
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
components:
  schemas:
    Customer:
      type: object
      x-examples:
        example:
          companyName: string
          externalRefNumber: string
          currency: string
          status: string
          parentCompanyId: string
          accountManagerId: string
          registrationNumber: string
          taxNumber: string
          notes: string
          creditAmountMax: 0
          creditDaysMax: 0
          pauseWorkflow: true
          contact:
            - firstName: string
              lastName: string
              middleName: string
              email: johndoe@peakflo.co
              phone: '6591234567'
              isMainContact: false
      description: The customer model
      properties:
        companyName:
          type: string
          description: The company name
        externalRefNumber:
          type: string
          description: The company Id
        currency:
          type: string
          description: The customers currency. Must be a ISO 4217 code
        status:
          type: string
          description: The status of the company
        parentCompanyId:
          type: string
          description: The customers parent companyId
        accountManagerId:
          type: string
          description: The account manager Id
        registrationNumber:
          type: string
          description: The company registration number
        taxNumber:
          type: string
          description: The company tax number
        notes:
          type: string
          description: Notes
        creditAmountMax:
          type: number
          description: Maximum amount upto which a credit is allowed
        creditDaysMax:
          type: number
          description: Maximum amount upto which a credit is allowed
        pauseWorkflow:
          type: boolean
          description: Indicate whether workflow is paused for this company or not. If paused then no actions will take place.
        contact:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
      required:
        - companyName
        - externalRefNumber
        - currency
        - status
    Contact:
      required:
        - email
        - firstName
        - lastName
        - phone
      type: object
      properties:
        firstName:
          type: string
          description: The first name of the contact
        lastName:
          type: string
          description: The last name of the contact
        middleName:
          type: string
          description: The middle name of the contact
        email:
          type: string
          description: The email Id of the contact
          example: johndoe@peakflo.co
        phone:
          type: string
          description: The phone number of the contact along with country code
          example: '6591234567'
        isMainContact:
          type: boolean
          description: Indicate if this is the main contact.
          default: false
      description: The contact model
