openapi: 3.0.1
info:
  title: Peakflo API
  description: 'The Peakflo API follows REST. Our APIs are organised as resource-oriented URLs, returns JSON responses.  They return standard HTTP response codes. You will need a JWT token to access the resources you are authorized to. '
  contact:
    url: 'https://peakflo.co/'
    email: info@peakflo.co
  x-logo:
    url: 'https://assets.dorik.com/5fa7a91326674600114e7aca/images/logo_black_zv0e3kxb.png'
    altText: Peakflo logo
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  url: 'https://docs.peakflo.co'
servers:
  - url: 'https://virtserver.swaggerhub.com/hari3/customer/1.0.0'
tags:
  - name: Customers
    description: The customer
  - name: Contacts
    description: The customers contact
  - name: Invoices
    description: The customers invoices
  - name: Payments
    description: The customers payments
  - name: Credit Notes
    description: The customers credit notes
paths:
  /customers:
    post:
      tags:
        - Customers
      summary: Add a customer
      description: Add a new customer
      operationId: add-customer
      requestBody:
        description: Customer to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
            examples:
              Example:
                value:
                  companyName: Mc win pte ltd
                  externalRefNumber: 1245a32
                  currency: USD
                  status: active
                  parentCompanyId: 23oc2344
                  accountManagerId: df34lvifmfkfef34r333
                  creditAmountMax: 10000
                  creditDaysMax: 20
                  pauseWorkflow: false
                  contact:
                    - firstName: Peter
                      lastName: Wong
                      email: peterwong@mcwin.com
                      phone: '6591234567'
                      isMainContact: false
        required: false
      responses:
        '201':
          description: customer created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
              examples:
                Example:
                  value:
                    companyName: Mc win pte ltd
                    externalRefNumber: 1245a32
                    currency: USD
                    status: active
                    parentCompanyId: 23oc2344
                    accountManagerId: df34lvifmfkfef34r333
                    creditAmountMax: 10000
                    creditDaysMax: 20
                    pauseWorkflow: false
                    contact:
                      - firstName: Peter
                        lastName: Wong
                        email: peterwong@mcwin.com
                        phone: '6591234567'
                        isMainContact: false
        '400':
          description: Invalid input
          content: {}
        '409':
          description: Customer already exists
          content: {}
      x-codegen-request-body-name: Customer
    parameters: []
  '/customers/{customerId}':
    put:
      tags:
        - Customers
      summary: 'Update a customer '
      description: Update an existing customer
      operationId: update-customer
      parameters:
        - name: customerId
          in: path
          description: The customer externalRefNumber
          required: true
          schema:
            type: string
      requestBody:
        description: Customer to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
            examples:
              Example:
                value:
                  companyName: Mc win pte ltd
                  externalRefNumber: 1245a32
                  currency: USD
                  status: active
                  parentCompanyId: 23oc2344
                  accountManagerId: df34lvifmfkfef34r333
                  creditAmountMax: 45000
                  creditDaysMax: 20
                  pauseWorkflow: false
                  contact:
                    - firstName: Peter
                      lastName: Wong
                      email: peterwong@mcwin.com
                      phone: '6591234567'
                      isMainContact: false
        required: false
      responses:
        '200':
          description: Updated customer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
              examples:
                Example:
                  value:
                    companyName: Mc win pte ltd
                    externalRefNumber: 1245a32
                    currency: USD
                    status: active
                    parentCompanyId: 23oc2344
                    accountManagerId: df34lvifmfkfef34r333
                    creditAmountMax: 45000
                    creditDaysMax: 20
                    pauseWorkflow: false
                    contact:
                      - firstName: Peter
                        lastName: Wong
                        email: peterwong@mcwin.com
                        phone: '6591234567'
                        isMainContact: false
        '400':
          description: Bad request
          content: {}
        '404':
          description: Not Found
        '409':
          description: Customer doesnot exist
          content: {}
      x-codegen-request-body-name: Customer
    delete:
      tags:
        - Customers
      summary: ''
      operationId: delete-customer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      description: Delete a customer
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
        description: The customer externalRefNumber
  '/customers/{customerId}/contacts':
    post:
      summary: add-contact
      tags:
        - Contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              examples:
                Example:
                  value:
                    firstName: Peter
                    lastName: Wong
                    email: peterwong@mcwin.com
                    phone: '6591234567'
                    isMainContact: false
        '400':
          description: Bad Request
        '409':
          description: Conflict
      operationId: add-contact
      description: Add a contact to existing customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contact'
            examples:
              Example:
                value:
                  firstName: Peter
                  lastName: Wong
                  email: peterwong@mcwin.com
                  phone: '6591234567'
                  isMainContact: false
        description: Contact to add
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
        description: The customer externalRefNumber
  '/customers/{customerId}/contacts/{contactId}':
    parameters:
      - schema:
          type: string
        name: contactId
        in: path
        required: true
        description: The Id of the contact to update or delete
      - schema:
          type: string
        name: customerId
        in: path
        required: true
        description: The customer externalRefNumber
    put:
      summary: update-contact
      tags:
        - Contacts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contact'
              examples:
                Example:
                  value:
                    firstName: Peter
                    lastName: Wong
                    email: peterwong@mcwin.com
                    phone: '6591234567'
                    isMainContact: false
        '404':
          description: Not Found
        '409':
          description: Conflict
      operationId: update-contact
      description: Update a contact
    delete:
      summary: delete-contact
      tags:
        - Contacts
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      operationId: delete-contact
      description: Delete a contact
components:
  schemas:
    Customer:
      type: object
      x-examples:
        Example:
          companyName: string
          externalRefNumber: string
          currency: USD
          status: active
          parentCompanyId: string
          accountManagerId: string
          registrationNumber: string
          taxNumber: string
          notes: string
          creditAmountMax: 0
          creditDaysMax: 0
          pauseWorkflow: true
          contact:
            - firstName: string
              lastName: string
              middleName: string
              email: johndoe@peakflo.co
              phone: '6591234567'
              isMainContact: false
      description: The customer model
      properties:
        companyName:
          type: string
          description: The company name
        externalRefNumber:
          type: string
          description: The company Id
        currency:
          type: string
          description: The customers currency. Must be a ISO 4217 code
        status:
          type: string
          description: The status of the company
          enum:
            - unknow
            - active
            - archived
          example: active
        parentCompanyId:
          type: string
          description: The customers parent companyId
        accountManagerId:
          type: string
          description: The account manager Id for the customer
        registrationNumber:
          type: string
          description: The company registration number
        taxNumber:
          type: string
          description: The company tax number
        notes:
          type: string
          description: Notes
        creditAmountMax:
          type: number
          description: Maximum amount upto which a credit is allowed
        creditDaysMax:
          type: number
          description: Maximum amount upto which a credit is allowed
        pauseWorkflow:
          type: boolean
          description: Indicate whether workflow is paused for this company or not. If paused then no actions will take place.
        contact:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        statementFile:
          type: string
          description: The statement file
        Address:
          type:
            - string
            - array
          description: The customers addresses
          items:
            $ref: '#/components/schemas/Address'
      required:
        - companyName
        - externalRefNumber
        - currency
        - status
        - parentCompanyId
    Contact:
      required:
        - email
        - firstName
        - lastName
        - phone
      type: object
      properties:
        firstName:
          type: string
          description: The first name of the contact
        lastName:
          type: string
          description: The last name of the contact
        middleName:
          type: string
          description: The middle name of the contact
        email:
          type: string
          description: The email Id of the contact
          example: johndoe@peakflo.co
        phone:
          type: string
          description: The phone number of the contact along with country code
          example: '6591234567'
        isMainContact:
          type: boolean
          description: Indicate if this is the main contact.
          default: false
      description: The contact model
    LineItem:
      description: The line item
      type: object
      properties:
        description:
          type: string
          description: Description about line item
        itemName:
          type: string
          description: Item name
        unitAmount:
          type: number
          description: Amount per unit for the line item
        quantity:
          type: number
          description: 'Number of units '
        discountAmount:
          type: number
          description: Discount on total amount
        subTotal:
          type: number
          description: The Subtotal
        taxAmount:
          type: number
          description: The tax amount
        totalAmount:
          type: number
          description: The total amount
      required:
        - itemName
        - unitAmount
        - quantity
    Attachment:
      description: The attachment
      type: object
      properties:
        id:
          type: string
          description: Unique attachment Id
        name:
          type: string
          description: 'Name of the attachment '
        dateCreated:
          type: string
          description: The date at which the attachment created. Follow ISO 8601 format
        contentType:
          type: string
          description: Content type of attachment
        fileSize:
          type: number
          description: The size of attachment
        data:
          type: string
          description: The attachment data
        fileType:
          $ref: '#/components/schemas/FileType'
      required:
        - id
        - name
        - contentType
        - data
    FileType:
      title: FileType
      type: string
      enum:
        - cabinet
        - invoice
        - statement
        - transaction
        - other
      description: The supported file types
      x-examples:
        Example: Invoice
    Invoice:
      description: ''
      type: object
      properties:
        invoiceId:
          type: string
          description: The invoiceId
        customerRef:
          type: string
          minLength: 1
          description: The customer Ref or Id
        issueDate:
          type: string
          minLength: 1
          description: Invoice issue date. Follow ISO8601 format
          example: '2021-04-28T12:30:00'
        dueDate:
          type: string
          minLength: 1
          description: The invoice due date. Follow ISO8601 format
        modifiedDate:
          type: string
          minLength: 1
          description: The invoice modified date. Follow ISO8601 format
        paidOnDate:
          description: The invoice paid date. Follow ISO8601 format
          type: string
        currency:
          type: string
          minLength: 1
          description: The invoice currency. Follow ISO 4217 code
        currencyRate:
          type: number
          description: The currency rate to convert currency to base currency
        lineItems:
          type: array
          uniqueItems: true
          description: The invoice line items
          items:
            $ref: '#/components/schemas/LineItem'
        totalAmount:
          type: number
          description: The total invoice amount
        totalDiscount:
          type: number
          description: Discount on invoice total amount
        totalTaxAmount:
          type: number
          description: Total tax amount on invoice
        amountDue:
          type: number
          description: Amount due on invoice
        status:
          type: string
          enum:
            - Draft
            - Submitted
            - PartiallyPaid
            - Void
            - Paid
          example: Paid
          default: Draft
          description: The invoice status
        note:
          type: string
          description: Notes about invoice
        attachments:
          type: array
          uniqueItems: true
          description: The invoice attachments
          items:
            $ref: '#/components/schemas/Attachment'
      required:
        - invoiceId
        - customerRef
        - issueDate
        - currency
        - totalAmount
    Address:
      description: The customers address
      type: object
      properties:
        type:
          type: string
          minLength: 1
          description: The address type
        line1:
          type: string
          minLength: 1
          description: The address line 1
        line2:
          type: string
          minLength: 1
        city:
          type: string
          minLength: 1
          description: The city
        region:
          type: string
          minLength: 1
          description: The region
        country:
          type: string
          minLength: 1
          description: The country
        postalCode:
          type: string
          minLength: 1
          description: The postal code
      required:
        - line1
        - city
        - country
        - postalCode
